spring:
  profiles:
    active: local

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true